### ISSUE TITLE
Fedora result?

### ISSUE THREAD

**Issue by rugk** [aviwad/librehunt#17]
![image](https://user-images.githubusercontent.com/11966684/58379731-ec2aba80-7fa7-11e9-84de-d988182da999.png)

Some things I don't agree on:
* Extreme security: I have selected "No extreme security", so I assume this here categorizes it as "Fedora has an extreme security."
  I don't think this is true, it's just a usual GNOME desktop/distro etc. Qubes OS would be "extreme security" for me.
* Touch support. Fedora with GNOME has excellent touch support (I use it like this). For this here, I've selected "no, I don't want touch" however, so I am surprised it is still a match. Or does it just show "extra features" such as touch support, as "matches"?

**Comment by aviwad** [comment]
first one, I thought "extreme security" because of the SElinux, but ubuntu has apparmour, so you're right
second one, yeah, touch is one of the extra matches that are more like a "I don't care" rather than a yes or no, because someone without touch is compatible with a touch-supported distro. but this is all broken, I get your point

**Comment by aviwad** [comment]
extreme security is gone

**Comment by aviwad** [comment]
this issue is fixed because librehunt now shows the details of the distro, not only whether it matches or not :D
